import Head from 'next/head'
import Message from "../components/message"
import { useEffect, useState } from "react"
import { db } from "../utils/firebase"
import { collection, onSnapshot, orderBy, query } from "firebase/firestore"
import Link from "next/link"

export default function Home() {

  const [allPosts, setAllPosts] = useState([])

  const getPosts = async () => {
    const collectionRef = collection(db, "posts")
    const q = query(collectionRef, orderBy("timestamp", "desc"))
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    })
    return unsubscribe
  }

  useEffect(() => {
    getPosts()
  }, [])

  return (
    <div className="px-10">
      <Head>
        <title>Howdy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/howdy.ico" />
      </Head>

      <div className="p-8 bg-gray-100 my-12 font-medium">
        <h2 className="font-bold text-lg py-2">The wall:</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{pathname:`/${post.id}`, query:{...post}}}>
              <button className="font-medium rounded-lg bg-yellow-500 text-white py-2 px-4 rounded-mg textx-10px">
                {post.comments?.length > 0 ? post.comments?.length : 0} Comment(s)
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  )
}
